#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# a specified text in between each iteration.
#   Displays a specified text in between each iteration.

while true

do

  echo "To infinity and beyond"

  sleep 2

  trap 'echo "I am invincible!!!"' SIGTERM 

done
